version: '3.9'

services:
  django:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    restart: always
    networks:
      - backend

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    restart: always
    networks:
      - backend

  celery:
    build: .
    command: celery -A Projeto worker --concurrency=4 --loglevel=info
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - redis
      - django
    restart: always
    networks:
      - backend

  flower:
    build: .
    command: celery -A Projeto flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge 